### ISSUE TITLE
Error with prefix replacement running panel at the shell, but not on a notebook

### ISSUE THREAD

**Issue by emiliom** [conda-forge/panel-feedstock#25] opened 2020-04-17 22:04 UTC
Issue:

I have a holoviz conda env (`holoviztrocas_panelapp_latest`) I use for a panel app. I ran the app on a notebook just now, using the env, w/o any problems. With the environment activated, I then tried to launch the panel from the shell via `$ panel serve --show --port 5009 trocas_pannelapp_1.ipynb` and got this error:
```
/home/mayorga/miniconda/envs/holoviztrocas_panelapp_latest/bin/panel: 2: exec: /home/conda/feedstock_root/build_artifacts/panel_1583934197818
/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python: not found
```
That "feedstock ... placehold_placehold_ ...." error is an error I've gotten at other times, including with previous iterations of the conda environment, but I eventually move past it w/o figuring out why it's happening. I get the same error when I issue the statement from the notebook where I'm running the panel app, prefixed by `!`.

Here's an initial assessment from @ocefpaf: Something is wrong with the prefix replacement there. The `_h_env_placehold...` should become your local `$PREFIX`. 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /home/mayorga/miniconda/envs/holoviztrocas_panelapp_latest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.1                      py_0    conda-forge
bokeh                     1.4.0                    py37_0    conda-forge
boost-cpp                 1.72.0               h8e57a91_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cachey                    0.1.1                      py_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
cartopy                   0.17.0          py37h88e1628_1010    conda-forge
certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
cffi                      1.14.0           py37hd463f26_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
cftime                    1.0.4.2          py37hc1659b7_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
click                     7.1.1              pyh8c360ce_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.3.0                      py_0    conda-forge
colorcet                  2.0.1                      py_0    conda-forge
cryptography              2.8              py37hb09aad4_2    conda-forge
curl                      7.68.0               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.12.0                     py_0    conda-forge
dask-core                 2.12.0                     py_0    conda-forge
datashader                0.10.0                     py_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
deprecated                1.2.7                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
distributed               2.12.0                   py37_0    conda-forge
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fastparquet               0.3.3            py37hc1659b7_0    conda-forge
fiona                     1.8.9.post2      py37hdff7cfa_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
gdal                      2.4.4            py37h5f563d9_0    conda-forge
geopandas                 0.7.0                      py_1    conda-forge
geos                      3.8.0                he1b5a44_1    conda-forge
geotiff                   1.5.1                h38872f0_8    conda-forge
geoviews                  1.6.6                      py_1    conda-forge
geoviews-core             1.6.6                      py_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3          py37he00f558_1003    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
holoviews                 1.12.7                     py_0    conda-forge
hvplot                    0.5.2                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.9                        py_1    conda-forge
imageio                   2.8.0                      py_0    conda-forge
importlib-metadata        1.5.0            py37hc8dfbb8_1    conda-forge
importlib_metadata        1.5.0                         1    conda-forge
ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge
ipython                   7.13.0           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.16.0           py37hc8dfbb8_1    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.0.0                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
kealib                    1.4.12               hec59c27_0    conda-forge
kiwisolver                1.1.0            py37h99015e2_1    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.68.0               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgdal                   2.4.4                h2b6fda6_0    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             hb574062_1011    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libllvm9                  9.0.1                hc9558a2_0    conda-forge
libnetcdf                 4.7.3           nompi_h9f9fd6a_101    conda-forge
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     12.2                 hae5116b_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialindex           1.9.3                he1b5a44_3    conda-forge
libspatialite             4.3.0a            ha48a99a_1034    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvm-openmp               9.0.1                hc9558a2_2    conda-forge
llvmlite                  0.31.0           py37h8b12597_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
mapclassify               2.2.0                      py_0    conda-forge
markdown                  3.2.1                      py_0    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
marshmallow               3.5.0                      py_0    conda-forge
matplotlib-base           3.2.0            py37h250f245_1    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
msgpack-python            1.0.0            py37hc9558a2_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.3           nompi_py37hd35fb8e_102    conda-forge
networkx                  2.4                        py_1    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numba                     0.48.0           py37hb3f55d8_0    conda-forge
numpy                     1.18.1           py37h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openpyxl                  3.0.3                      py_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
owslib                    0.19.2                     py_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.2            py37h0da4684_0    conda-forge
pandoc                    2.9.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
panel                     0.8.1              pyh8c360ce_0    conda-forge
param                     1.9.3                      py_0    conda-forge
parso                     0.6.2                      py_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0                    py37_0    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pillow                    7.0.0            py37h718be6c_1    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 hf1211e9_0    conda-forge
proj                      6.3.0                hc80f0dc_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt-toolkit            3.0.4                      py_0    conda-forge
prompt_toolkit            3.0.4                         0    conda-forge
psutil                    5.7.0            py37h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycparser                 2.20                       py_0    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pykdtree                  1.3.1           py37hc1659b7_1002    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    2.5.0            py37h8ff28aa_0    conda-forge
pyqt                      5.12.3           py37hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py37h8f50634_1    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6           h357f687_4_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-snappy             0.5.4            py37h7cfaab3_1    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyviz_comms               0.7.4              pyh8c360ce_0    conda-forge
pywavelets                1.1.1            py37hc1659b7_0    conda-forge
pyyaml                    5.3              py37h516909a_0    conda-forge
pyzmq                     19.0.0           py37hac76be4_1    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtconsole                 4.7.1                      py_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.23.0                   py37_0    conda-forge
rtree                     0.9.4            py37h8526d28_1    conda-forge
scikit-image              0.16.2           py37hb3f55d8_0    conda-forge
scikit-learn              0.22.2.post1     py37hcdab131_0    conda-forge
scipy                     1.4.1            py37h921218d_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                46.0.0           py37hc8dfbb8_2    conda-forge
shapely                   1.7.0            py37hb106bac_1    conda-forge
six                       1.14.0                     py_1    conda-forge
snappy                    1.1.8                he1b5a44_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thrift                    0.11.0          py37he1b5a44_1001    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
tqdm                      4.43.0                     py_0    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webargs                   6.0.0                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
wrapt                     1.12.1           py37h8f50634_1    conda-forge
xarray                    0.15.0                     py_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : holoviztrocas_panelapp_latest
    active env location : /home/mayorga/miniconda/envs/holoviztrocas_panelapp_latest
            shell level : 2
       user config file : /home/mayorga/.condarc
 populated config files : /home/mayorga/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __glibc=2.27
       base environment : /home/mayorga/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mayorga/miniconda/pkgs
                          /home/mayorga/.conda/pkgs
       envs directories : /home/mayorga/miniconda/envs
                          /home/mayorga/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.3 Linux/5.3.0-7629-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : /home/mayorga/.netrc
           offline mode : False
```
</details>

**Comment by ocefpaf** [comment] 2020-04-19 16:08
> I then tried to launch the panel from the shell via $ panel serve --show --port 5009 trocas_pannelapp_1.ipynb and got this error:

I can confirm that the 0.8.1 version did not have the proper prefix replacement as expected. Everything seems to work fine with 0.9.5 though. Can you upgrade? If not will have to rebuild the older version.

**Comment by philippjfr** [comment] 2020-04-19 16:40
Upgrading should work but we'll have to fix 0.8.x releases since that's the last version to support python 2.

**Comment by ocefpaf** [comment] 2020-04-19 17:13
OK. I'll create a branch and see if we can fix that.

**Comment by emiliom** [comment] 2020-04-19 23:12
> Everything seems to work fine with 0.9.5 though. Can you upgrade?

That worked. I created a new environment that installed panel 0.9.5. `panel serve` now works, and my app works fine with the latest versions of holoviz packages. Thanks!

**Comment by ocefpaf** [comment] 2020-04-29 18:47
@emiliom I'm closing this/ The new v0.8.x are also up and should work too.

**Closed by ocefpaf** 2020-04-29 18:47 UTC

**Comment by philippjfr** [comment] 2020-04-29 18:49
@ocefpaf Thanks so much!
